[package]
name = "dump_syms"
version = "0.0.1"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.33.0"
goblin = "0.0.23"
symbolic-debuginfo = "6.1.3"
pdb = "0.5.0"
uuid = "0.7.2"